export const actions = {
	DISTRIBUTE_REPLAY_ACTION: "DISTRUBUTE_REPLAY_ACTION",
	DISTRIBUTE_UP_TO_DATE: "DISTRUBUTE_UP_TO_DATE",
	DISTRIBUTE_ROLL_BACK_TO_SNAPSHOT: "DISTRUBUTE_ROLL_BACK_TO_SNAPSHOT",
};

export const states = {
	STARTING_UP: "STARTING_UP",
	UP_TO_DATE: "UP_TO_DATE",
	REPLAYING_ACTIONS: "REPLAYING_ACTIONS",
	ROLLED_BACK: "ROLLED_BACK",
};
